<?php
/**
 * Регистрация полей ACF
 *
 * Содержит функции для регистрации полей ACF,
 * перенесенных из админки в код.
 *
 * @package rshop
 * @version 1.0.0
 */

if (!defined('ABSPATH')) {
    exit; // Exit if accessed directly
}

/**
 * Регистрация групп полей ACF
 */
add_action('acf/include_fields', function() {
    if (!function_exists('acf_add_local_field_group')) {
        return;
    }

    // Группа полей для карточки товара
    acf_add_local_field_group(array(
        'key' => 'group_5ee494c68c406',
        'title' => 'Дополнительно (карточка товара)',
        'fields' => array(
            array(
                'key' => 'field_5ee494e51948b',
                'label' => 'Дополнительный параметр (под названием)',
                'name' => 'dopolnitelnye_parametry',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5f22866c8506e',
                'label' => 'Средняя площадь',
                'name' => 'srednyaya_ploshhad',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5f2287bd1772c',
                'label' => 'Цена за дм^2',
                'name' => 'cena_za_dm2',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5f2289971394f',
                'label' => 'Вариативный атрибут (толщина, фасовка, высота ворса и тп)',
                'name' => 'varia_attribute',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5f7c7cda1fb41',
                'label' => 'Тип кожи',
                'name' => 'tip_kozhi',
                'aria-label' => '',
                'type' => 'taxonomy',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'taxonomy' => 'pa_kozha',
                'field_type' => 'checkbox',
                'add_term' => 0,
                'save_terms' => 1,
                'load_terms' => 1,
                'return_format' => 'object',
                'multiple' => 0,
                'allow_null' => 0,
                'bidirectional_target' => array(),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'product',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => false,
    ));

    // Группа полей для системы лояльности
    acf_add_local_field_group(array(
        'key' => 'group_646f6520995f8',
        'title' => 'Система лояльности',
        'fields' => array(
            array(
                'key' => 'field_646f652a9553c',
                'label' => 'Номер карты лояльности',
                'name' => 'loyal_card_number',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'current_user',
                    'operator' => '==',
                    'value' => 'viewing_back',
                ),
                array(
                    'param' => 'user_form',
                    'operator' => '==',
                    'value' => 'edit',
                ),
            ),
            array(
                array(
                    'param' => 'user_form',
                    'operator' => '==',
                    'value' => 'all',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'acf_after_title',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ));

    // Группа полей для шапки сайта
    acf_add_local_field_group(array(
        'key' => 'group_66e4105a2246c',
        'title' => 'Шапка сайта',
        'fields' => array(
            array(
                'key' => 'field_66e4105a80eaa',
                'label' => 'Часы работы',
                'name' => 'header_hours',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_66e411d931131',
                'label' => 'Перечеркнутые часы работы в будни',
                'name' => 'header_hours_strike',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_66e4114131130',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_66e4114131130',
                'label' => 'Добавить перечеркнутое время?',
                'name' => 'strike_header_hours_checked',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => 'Добавить перечеркнутое время?',
                'default_value' => 0,
                'allow_in_bindings' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
                'ui' => 1,
            ),
            array(
                'key' => 'field_66e4109d80eab',
                'label' => 'Часы работы в сб',
                'name' => 'header_hours_sat',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_66e4137a01656',
                'label' => 'Перечеркнутые часы работы в субботу',
                'name' => 'header_hours_strike_sat',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_66e4136e01655',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_66e4136e01655',
                'label' => 'Добавить перечеркнутое время?',
                'name' => 'strike_header_hours_checked_sat',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => 'Добавить перечеркнутое время?',
                'default_value' => 0,
                'allow_in_bindings' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
                'ui' => 1,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'site-header-options',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'acf_after_title',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ));

    // Группа полей для слайдера
    acf_add_local_field_group(array(
        'key' => 'group_5ef47f50ac246',
        'title' => 'Слайдер',
        'fields' => array(
            array(
                'key' => 'field_658c2164170fd',
                'label' => 'Слайдер',
                'name' => 'carousel-slider',
                'aria-label' => '',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'table',
                'button_label' => 'Добавить',
                'sub_fields' => array(
                    array(
                        'key' => 'field_658c21ad170fe',
                        'label' => 'Слайд',
                        'name' => 'slide',
                        'aria-label' => '',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_slide_tab_main',
                                'label' => 'Основное',
                                'name' => '',
                                'aria-label' => '',
                                'type' => 'accordion',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'open' => 1,
                                'multi_expand' => 1,
                                'endpoint' => 0,
                            ),
                            array(
                                'key' => 'field_658c21c4170ff',
                                'label' => 'Слайд вкл/выкл',
                                'name' => 'slide_enabled',
                                'aria-label' => '',
                                'type' => 'true_false',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '25',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'message' => '',
                                'default_value' => 0,
                                'ui' => 1,
                                'ui_on_text' => 'Вкл',
                                'ui_off_text' => 'Выкл',
                            ),
                            array(
                                'key' => 'field_658c221b17101',
                                'label' => 'Заголовок',
                                'name' => 'slide_headline',
                                'aria-label' => '',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '75',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => 'Заголовок слайда',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'field_658c222f17102',
                                'label' => 'Кнопка',
                                'name' => 'slide_sub_button',
                                'aria-label' => '',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '50',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => 'Подробнее',
                                'placeholder' => 'Текст кнопки',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'field_658c226217103',
                                'label' => 'Ссылка',
                                'name' => 'slide_link',
                                'aria-label' => '',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '50',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => 'Укажите URL для кнопки',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            // Таб изображений
                            array(
                                'key' => 'field_slide_tab_images',
                                'label' => 'Изображения',
                                'name' => '',
                                'aria-label' => '',
                                'type' => 'accordion',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'open' => 0,
                                'multi_expand' => 1,
                                'endpoint' => 0,
                            ),
                            array(
                                'key' => 'field_658c21eb17100',
                                'label' => 'Изображение (десктоп)',
                                'name' => 'slide_image',
                                'aria-label' => '',
                                'type' => 'image',
                                'instructions' => 'Основное изображение для всех устройств',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '60',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'array',
                                'preview_size' => 'medium',
                                'library' => 'all',
                                'min_width' => '',
                                'min_height' => '',
                                'min_size' => '',
                                'max_width' => '',
                                'max_height' => '',
                                'max_size' => '',
                                'mime_types' => '',
                            ),
                            array(
                                'key' => 'field_slide_image_desktop_alt',
                                'label' => 'Alt-текст',
                                'name' => 'slide_image_desktop_alt',
                                'aria-label' => '',
                                'type' => 'text',
                                'instructions' => 'Описание изображения для всех устройств (для SEO и доступности)',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '40',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => 'Описание изображения',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'field_use_responsive_images',
                                'label' => 'Разные изображения для устройств',
                                'name' => 'use_responsive_images',
                                'aria-label' => '',
                                'type' => 'true_false',
                                'instructions' => 'Включите, чтобы добавить отдельные изображения для планшетов и мобильных',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'message' => '',
                                'default_value' => 0,
                                'ui' => 1,
                                'ui_on_text' => 'Вкл',
                                'ui_off_text' => 'Выкл',
                            ),
                            // Планшетное изображение (условно)
                            array(
                                'key' => 'field_tablet_slide_image',
                                'label' => 'Изображение (планшет)',
                                'name' => 'slide_image_tablet',
                                'aria-label' => '',
                                'type' => 'image',
                                'instructions' => 'Изображение для планшетов (768px - 1199px)',
                                'required' => 0,
                                'conditional_logic' => array(
                                    array(
                                        array(
                                            'field' => 'field_use_responsive_images',
                                            'operator' => '==',
                                            'value' => '1',
                                        ),
                                    ),
                                ),
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'array',
                                'preview_size' => 'medium',
                                'library' => 'all',
                                'min_width' => '',
                                'min_height' => '',
                                'min_size' => '',
                                'max_width' => '',
                                'max_height' => '',
                                'max_size' => '',
                                'mime_types' => '',
                            ),
                            // Мобильное изображение (условно)
                            array(
                                'key' => 'field_mobile_slide_image',
                                'label' => 'Изображение (мобильный)',
                                'name' => 'slide_image_mobile',
                                'aria-label' => '',
                                'type' => 'image',
                                'instructions' => 'Изображение для мобильных устройств (до 767px)',
                                'required' => 0,
                                'conditional_logic' => array(
                                    array(
                                        array(
                                            'field' => 'field_use_responsive_images',
                                            'operator' => '==',
                                            'value' => '1',
                                        ),
                                    ),
                                ),
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'array',
                                'preview_size' => 'medium',
                                'library' => 'all',
                                'min_width' => '',
                                'min_height' => '',
                                'min_size' => '',
                                'max_width' => '',
                                'max_height' => '',
                                'max_size' => '',
                                'mime_types' => '',
                            ),
                            
                            // Таб настроек
                            array(
                                'key' => 'field_slide_tab_settings',
                                'label' => 'Настройки',
                                'name' => '',
                                'aria-label' => '',
                                'type' => 'accordion',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'open' => 0,
                                'multi_expand' => 1,
                                'endpoint' => 0,
                            ),
                            array(
                                'key' => 'field_slide_title_position',
                                'label' => 'Положение заголовка',
                                'name' => 'slide_title_position',
                                'aria-label' => '',
                                'type' => 'range',
                                'instructions' => 'Положение заголовка по вертикали (0% - верх, 50% - центр, 100% - низ)',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '50',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => 40,
                                'min' => 0,
                                'max' => 100,
                                'step' => 5,
                                'prepend' => '',
                                'append' => '%',
                            ),
                            array(
                                'key' => 'field_slide_button_position',
                                'label' => 'Положение кнопки',
                                'name' => 'slide_button_position',
                                'aria-label' => '',
                                'type' => 'range',
                                'instructions' => 'Положение кнопки по вертикали (0% - верх, 50% - центр, 100% - низ)',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '50',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => 60,
                                'min' => 0,
                                'max' => 100,
                                'step' => 5,
                                'prepend' => '',
                                'append' => '%',
                            ),
                            array(
                                'key' => 'field_slide_overlay_opacity',
                                'label' => 'Затемнение изображения',
                                'name' => 'slide_overlay_opacity',
                                'aria-label' => '',
                                'type' => 'range',
                                'instructions' => 'Настройка степени затемнения изображения (0% - без затемнения, 100% - полностью темное). По умолчанию: 10%',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => 10,
                                'min' => 0,
                                'max' => 100,
                                'step' => 5,
                                'prepend' => '',
                                'append' => '%',
                            ),
                        ),
                        'parent_repeater' => 'field_658c2164170fd',
                    ),
                ),
                'rows_per_page' => 20,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'page',
                    'operator' => '==',
                    'value' => '33',
                ),
            ),
        ),
        'menu_order' => 2,
        'position' => 'acf_after_title',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ));
});

/**
 * Регистрация страницы опций для шапки сайта
 */
add_action('acf/init', function() {
    if (function_exists('acf_add_options_page')) {
        acf_add_options_page(array(
            'page_title' => 'Шапка сайта',
            'menu_slug' => 'site-header-options',
            'position' => '',
            'redirect' => false,
            'menu_icon' => array(
                'type' => 'dashicons',
                'value' => 'dashicons-clock',
            ),
            'icon_url' => 'dashicons-clock',
        ));
    }
}); 